name: 02-workflow-events

on: 
    push:
    pull_request:
    schedule:
        - cron: '*/1 * * * *'
    workflow_dispatch:

jobs: 
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: Show the trigger
              run: echo "I've been triggered by a ${GITHUB_EVENT_NAME} event."