name: 02-workflow-events

on: 
    push:
    workflow_dispatch:

jobs: 
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: Show the trigger
              run: echo echo "I've been triggered by a (n) ${{ github.event_name }}"
