name: 05 - 1 - Events Filters and Activity Types 

on: 
    pull_request:
        types:
            - opened
            - synchronize 
        branches:
                - main 

jobs: 
    echo:
        runs-on: ubuntu-latest
        steps:
          - runs: echo "Running whenever a PR is opened or synchronized AND base branch is main"
