name: 17- Custom Actions - Composite
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
        run:
            working-directory: ${{ env.working-directory }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node and NPM Dependencies
        uses: ./.github/actions/composite-cache-deps
        with:
          node-version: 20.x
          working-dir: 17-custom-action/react-app

      - name: Test
        run: npm run test
        working-directory: ${{ env.working-directory }} 

      - name: Build
        run: npm run build